### ISSUE TITLE
Move user_data to dedicated template files

### ISSUE THREAD

**Issue by lpaulmp** [fpco/terraform-aws-foundation#120] opened 2018-04-26 14:09 UTC
Move `user_data` inline scripts to dedicated template files.
```
user_data = <<END_INIT 
foo
END_INIT
```
template file
```
user_data = "${data.template_file.foo.rendered}"

data "template_file" "foo"{
  template = "${file("${path.module}/data/foo.tpl.sh")}"
}
```

**Comment by ketzacoatl** [comment] 2018-05-20 11:10
This is a duplicate of #109, closing in favor of the first ticket.

**Closed by ketzacoatl** 2018-05-20 11:10 UTC
