### ISSUE TITLE
Fix TFLint output to turn the build green

### ISSUE THREAD

**Issue by lpaulmp** [fpco/terraform-aws-foundation#129] opened 2018-05-08 01:02 UTC
[build](https://gitlab.fpcomplete.com/fpco-mirrors/terraform-aws-foundation/builds/5236)

```
../modules/bind-server/main.tf
	NOTICE:63 "iam_instance_profile" is not specified. If you want to change it, you need to recreate the instance. (aws_instance_not_specified_iam_profile)
../modules/dnsmasq-server/main.tf
	NOTICE:62 "iam_instance_profile" is not specified. If you want to change it, you need to recreate the instance. (aws_instance_not_specified_iam_profile)
../modules/vpn-gateway/main.tf
	NOTICE:29 "iam_instance_profile" is not specified. If you want to change it, you need to recreate the instance. (aws_instance_not_specified_iam_profile)
main.tf
	WARNING:348 Module source "../modules/init-snippet-gitlab-docker" is not pinned (terraform_module_pinned_source)

Result: 4 issues  (0 errors , 1 warnings , 3 notices)
```

**Comment by ketzacoatl** [comment] 2018-05-08 01:12
This is a duplicate of #107, closing in favor of the original

**Closed by ketzacoatl** 2018-05-08 01:12 UTC
