### ISSUE TITLE
move terraform-vpc to examples so it can be used as such

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#95] opened 2018-04-15 17:41 UTC
the `terraform-vpc` env is in https://github.com/fpco/terraform-aws-foundation/tree/master/packer/terraform-vpc. This is ideal for the packer builds (eg https://github.com/fpco/terraform-aws-foundation/blob/master/packer/ubuntu-trusty/build.sh#L11-L15), but not ideal for the user who would want to use this example via the registry.

**Comment by ketzacoatl** [comment] 2018-05-20 11:12
This should be easy to knock out in the week ahead, cc @mcgirr

**Comment by mcgirr** [comment] 2018-05-25 20:46
@ketzacoatl Will the packer build script need to be updated as well after `terraform-vpc` is moved, or is this just going to create a duplicate of the existing terraform code (for `terraform-vpc`) in a new example?

**Comment by mcgirr** [comment] 2018-05-25 21:55
The initial example is available on the [move-terraform-vpc branch](https://github.com/fpco/terraform-aws-foundation/tree/move-terraform-vpc/examples/terraform-vpc). 

The example does **not** include any build shell script for building AMI's with `packer`. I can add that if that was within the scope of what the example was intended to do. 

I also did not remove the [previous](https://github.com/fpco/terraform-aws-foundation/blob/master/packer/terraform-vpc/main.tf) `terraform-vpc` terraform code either since it's used by the AMI build script.

**Comment by ketzacoatl** [comment] 2018-05-26 04:37
> Will the packer build script need to be updated as well after terraform-vpc is moved, or is the intent of the issue to create a duplicate of the existing terraform code (for terraform-vpc) in a new example and leave the existing terraform configuration code here?

One copy is preferred. Updating the packer build script to use the new location probably makes the most sense.

**Comment by mcgirr** [comment] 2018-05-26 04:57
Sounds good. I will leave the existing packer build script in it's [current](https://github.com/fpco/terraform-aws-foundation/blob/master/packer/ubuntu-trusty/build.sh) location, but it will updated to be using the new location of the terraform configuration in [examples/terraform-vpc](https://github.com/fpco/terraform-aws-foundation/blob/move-terraform-vpc/examples/terraform-vpc/main.tf)

**Comment by mcgirr** [comment] 2018-05-28 00:13
@ketzacoatl The build script has been updated in the latest [commit](https://github.com/fpco/terraform-aws-foundation/commit/53d9ba71aa72d491857e536ade60ce17b0de4bdc) to reflect the new location of the terraform configuration.

**Closed** 2018-05-28 04:40 UTC
Labels: P1
